### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by Monkeyzc** [lefex/SYWebViewBridge#1]
WebView 没有释放

<img width="1415" alt="截屏2020-10-22 下午2 54 02" src="https://user-images.githubusercontent.com/16532120/96836747-fd674780-1477-11eb-94f7-d61501aeb419.png">

**Comment by lefex** [comment]
你好，感谢反馈：

今天是周末，看了下这个问题，原因如下：

[内存泄露的思考与解决方案](https://mp.weixin.qq.com/s/i7B66rrWsC7XbwSkx5pkNw)
